version: "3.5"
services:
  # --------------------------------------------- redis ---------------------------------------------
  #
  # 注意: 如没有必要，端口不要对外开放
  #
  # ----------------------------- 测试
  #
  # 暂时只有一个 redis 缓存，无主从
  # redis-cli -h 172.19.10.31 -p 9012 -a soT8qZ5sV1qrsBJJ
  zero.redis:
    container_name: zero.redis
    image: redis:7.0.4-alpine3.16
    ports:
      - "8087:9012"
    volumes:
      # 时区配置
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # 持久化目录
      - /data/services/fh-server/redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    command: redis-server --appendonly yes --port 9012 --requirepass "soT8qZ5sV1qrsBJJ" --dir /data --maxmemory 3000mb --maxmemory-policy volatile-ttl
    restart: unless-stopped
    networks:
      persist:
        ipv4_address: 172.19.10.31
networks:
  # 连接到外部已存在的网络
  # 由 docs/docker/etcd/docker-compose.yml 创建的网络
  persist:
    external:
      name: etcd_zero.network
